In [1]:
a = 123456789

In [7]:
l = [n for n in str(a)]
l

['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
l.count('1')

1

In [11]:
str(a).count('1')

1

In [12]:
a = 123456789123

In [13]:
str(a).count('1')


2

In [14]:
l = [40, 80, 60]

In [18]:
import numpy as np

In [19]:
l1 = np.array(l)
l1

array([40, 80, 60])

In [23]:
sum(l1 / 80 * 100)/len(l1)

75.0

In [24]:
l1

array([40, 80, 60])

In [25]:
max(l1)

80

In [28]:
l = map(int, input().split())
l

40 60 80


In [75]:
l1 = np.array(l)
print(sum((l1/max(l1))*100)/len(l1))

70.0


In [ ]:
import numpy as np

In [33]:
n = input()
l = np.array(list(map(int, input().split())))

3
30 50 70


In [34]:
l

array([30, 50, 70])

In [35]:
print(sum((l/max(l))*100)/len(l))

71.42857142857143


ox

In [40]:
l= 'ooxxoxxooo'
l = l.upper()
l

'OOXXOXXOOO'

In [44]:
num = 0
list1 = []
for i in l:
    if i == 'O':
        num += 1
        list1.append(num)
    else :
        num = 0
        list1.append(num)

In [46]:
sum(list1)

10

평균

In [49]:
sum([50, 50, 70, 80, 100])/ 5

70.0

In [51]:
2/5

0.4

In [52]:
sum([100, 95, 90, 80, 70, 60, 50])/ 7

77.85714285714286

In [53]:
4/7

0.5714285714285714

In [60]:
line = '6 50 60 70 80 90 100'
n,*l = map(int,line.split())


In [61]:
l

[50, 60, 70, 80, 90, 100]

In [62]:
for i in l:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [63]:
n

6

In [64]:
m = sum(l)/n
m

75.0

In [65]:
c = 0
for i in l:
    if i>m:
        c += 1
print(c/n)

0.5


In [66]:
line = '5 50 50 70 80 100'

In [67]:
n,*l = map(int,line.split())
m = sum(l)/n
c = 0
for i in l:
    if i>m:
        c += 1
print(f'{round(c/n,3)}%')

0.4%


In [74]:
nm = 40

print('%.3f%%'%(nm))

40.000%
