In [6]:
import numpy as np

In [7]:
L = [1,4,5,5,6,8,6,4]

In [10]:
A= np.array(L)
A

array([1, 4, 5, 5, 6, 8, 6, 4])

In [14]:
B=np.array(A,float)
A.array(float)

AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [15]:
L = [[1,2,3,4],[5,5,6,5],[8,6,4,6]]

In [16]:
mat = np.array(L)       # 3*4 matrix
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [17]:
mat.std()

1.846543317180028

In [20]:
mat.var()

3.409722222222222

In [23]:
np.mean(mat,axis=0)

array([4.66666667, 4.33333333, 4.33333333, 5.        ])

In [22]:
mat1 = np.array([[1,2,3,4],[4,5,6,7]])
vec1 = np.array([5,6,7,8])
mat1/vec1

array([[0.2       , 0.33333333, 0.42857143, 0.5       ],
       [0.8       , 0.83333333, 0.85714286, 0.875     ]])

In [26]:
sum(mat,axis=0)

TypeError: 'axis' is an invalid keyword argument for sum()

In [67]:
a = tuple()
type((3))

int

In [57]:
import numpy as np

In [2]:
l1 = [1,2,3,4,5,6]

In [3]:
l2 = [8,7,6,5,4,3]

In [6]:
t1 = np.array(l1)
t2 = np.array(l2)

In [58]:
t1.dtype

dtype('int32')

In [13]:
t1 = t1.reshape(2,3)

In [14]:
t2 = t2.reshape(3,2)

In [15]:
t1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
t2

array([[8, 7],
       [6, 5],
       [4, 3]])

In [18]:
t1+t2    # broadcasting operation의 제한존재

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [19]:
t1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
t1[0,1] = '2'
t1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
t1[0,0] = '22'
t1

array([[22,  2,  3],
       [ 4,  5,  6]])

In [22]:
array(float)

NameError: name 'array' is not defined

In [23]:
np.array(t1,float)

array([[22.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [24]:
array[0,0] = '100'

NameError: name 'array' is not defined

In [25]:
t1[0,0] = '100'

In [26]:
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [27]:
t1*2
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [28]:
np.array(t1,int)

array([[100,   2,   3],
       [  4,   5,   6]])

In [31]:
t1*2
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [33]:
np.array(t1,str)
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [34]:
t1*2

array([[200,   4,   6],
       [  8,  10,  12]])

In [35]:
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [36]:
type(t1)

numpy.ndarray

In [37]:
t1[0][0]

100

In [40]:
t2 = np.array(t1,float)
t2

array([[100.,   2.,   3.],
       [  4.,   5.,   6.]])

In [41]:
t1 = np.array(t2, str)

In [42]:
t1

array([['100.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0']], dtype='<U32')

In [43]:
t1 *2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

In [48]:
t1 = np.array(t1,int)
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [49]:
t1[0][0] = '100'
t1

array([[100,   2,   3],
       [  4,   5,   6]])

In [50]:
t1[0][0] = '200'
t1

array([[200,   2,   3],
       [  4,   5,   6]])

In [51]:
type(t1[0][0])

numpy.int32

In [68]:
L = [[1,2,3,4],[5,5,6,5],[8,6,4,6]]

In [69]:
mat = np.array(L)       # 3*4 matrix
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [72]:
mat[:,2]

array([3, 6, 4])

In [73]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
any(a>5)

True

In [75]:
all(a<0)

False

In [1]:
import pandas as pd

In [2]:
t= (1,2,3,4,5)

In [4]:
ts = pd.Series(t)

In [5]:
ts

0    1
1    2
2    3
3    4
4    5
dtype: int64