In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [5]:
np.any(a>5)

True

In [8]:
np.all(a>5)

False

In [10]:
test_a = np.array([1,3,0],float)
test_a

array([1., 3., 0.])

In [11]:
test_b = np.array([5,2,1], float)
test_b

array([5., 2., 1.])

In [12]:
test_a +test_b

array([6., 5., 1.])

In [13]:
test_a *test_b

array([5., 6., 0.])

In [14]:
test_a > test_b

array([False,  True, False])

In [15]:
test_a == test_b

array([False, False, False])

In [16]:
np.any(test_a>test_b)

True

In [17]:
np.all(test_a>test_b)

False

### boolean indexing

In [19]:
test_array = np.array([1,4,0,2,3,8,9,7])
test_array

array([1, 4, 0, 2, 3, 8, 9, 7])

In [20]:
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [24]:
test_array[test_array>3]

array([4, 8, 9, 7])

In [25]:
names = np.array(['bon','kim','jim','park'])
names

array(['bon', 'kim', 'jim', 'park'], dtype='<U4')

#### boolean index를 통해서 'kim'을 출력하시오

In [26]:
names[1]   # 인덱스 사용

'kim'

In [29]:
print(names[names == 'kim'])   # 조건 사용 추출

['kim']


#### names에서 'kim'이 아닌 사람을 boolean indexing으로 출력

In [31]:
print(names[names!='kim'])

['bon' 'jim' 'park']


#### boolean index를 통해서 0보다 큰 값만 출력

In [48]:
randarr = np.random.randn(7,4)   #.rand( 0~1 사이 값 추출), randn(0평균 표준편차1 에서 추출)
randarr

array([[ 1.62283445, -0.50479423, -1.25661202, -0.9805094 ],
       [ 0.0085836 , -0.0635776 , -1.01691582, -0.31114738],
       [-0.6642312 ,  1.43704419, -0.93208097,  0.15813994],
       [-0.02118231,  0.54024882,  0.42244747,  0.97509498],
       [ 0.02817479, -0.72083562, -0.52412527,  0.27326162],
       [ 1.64107272,  1.83569151, -1.57341046,  0.7067931 ],
       [ 1.20934484,  0.26992432,  2.17957058, -0.53001735]])

In [49]:
randarr[randarr>0]

array([1.62283445, 0.0085836 , 1.43704419, 0.15813994, 0.54024882,
       0.42244747, 0.97509498, 0.02817479, 0.27326162, 1.64107272,
       1.83569151, 0.7067931 , 1.20934484, 0.26992432, 2.17957058])

####  1~100까지 정수에서 20보다 크고 70보다 작은 3의 배수를 출력

In [59]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [67]:
np.logical_and(a>20, a<70, (a%3==0))    # logical_and는 조건이 2개까지만 적용됨

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [68]:
a[(a>20) & (a<70) & (a%3==0)]

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69])

### fancy index

In [70]:
arr = np.array([2,3,4,5,4,7,6,8,6])
arr

array([2, 3, 4, 5, 4, 7, 6, 8, 6])

In [71]:
arr[5]

7

In [72]:
arr[5:8]

array([7, 6, 8])

In [73]:
arr[:5]

array([2, 3, 4, 5, 4])

#### 1,5,6번 index요소를 가져오시오

In [75]:
arr[[1,5,6]]     # fancy index

array([3, 7, 6])