In [40]:
import pandas as pd
import numpy as np

# EDA

### test data

##### err

In [14]:
test_err = pd.read_csv('./data/test_err_data.csv')
test_err

user_id            time model_nm       fwver  errtype errcode
0           30000  20201101030227  model_1  04.16.3553       31       1
1           30000  20201101030227  model_1  04.16.3553       33       2
2           30000  20201101030228  model_1  04.16.3553       15       1
3           30000  20201101030256  model_1  04.16.3553       22       1
4           30000  20201101030300  model_1  04.16.3553       11       1
...           ...             ...      ...         ...      ...     ...
16532643    44998  20201130210050  model_1  04.16.3553       40       0
16532644    44998  20201130211831  model_1  04.16.3553       31       1
16532645    44998  20201130211832  model_1  04.16.3553       15       1
16532646    44998  20201130212259  model_1  04.16.3553       16       1
16532647    44998  20201130212316  model_1  04.16.3553       31       0

[16532648 rows x 6 columns]

##### quality

In [12]:
test_quality = pd.read_csv('./data/test_quality_data.csv')
test_quality

time  user_id       fwver  quality_0 quality_1  quality_2  \
0       20201128195000    30000  04.33.1261        0.0         0        0.0   
1       20201128195000    30000  04.33.1261        0.0         0        0.0   
2       20201128195000    30000  04.33.1261        0.0         0        0.0   
3       20201128195000    30000  04.33.1261        0.0         0        0.0   
4       20201128195000    30000  04.33.1261        0.0         0        0.0   
...                ...      ...         ...        ...       ...        ...   
747967  20201125180000    44997  04.22.1750        0.0         0        0.0   
747968  20201125180000    44997  04.22.1750        0.0         0        0.0   
747969  20201125180000    44997  04.22.1750        0.0         0        0.0   
747970  20201125180000    44997  04.22.1750        0.0         0        0.0   
747971  20201125180000    44997  04.22.1750        0.0         0        0.0   

        quality_3  quality_4 quality_5  quality_6 quality_7 quality_8  \
0               0          0         0          0         5         0   
1               0          0         0          0         5         0   
2               0          0         0          0         5         0   
3               0          0         0          0         5         0   
4               0          0         0          0         5         0   
...           ...        ...       ...        ...       ...       ...   
747967          0          0         2          0         0         0   
747968          0          0         0          0         0         0   
747969          0          0         0          0         0         0   
747970          0          0         0          0         0         0   
747971          0          0         0          0         0         0   

       quality_9 quality_10  quality_11  quality_12  
0              0          2           0           0  
1              0          2           0           0  
2              0          2           0           0  
3              0          2           0           0  
4              0          2           0           0  
...          ...        ...         ...         ...  
747967         0          3           0           0  
747968         0          3           0           0  
747969         0          3           0           0  
747970         0          3           0           0  
747971         0          3           0           0  

[747972 rows x 16 columns]

In [32]:
test_quality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 747972 entries, 0 to 747971
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   time        747972 non-null  int64  
 1   user_id     747972 non-null  int64  
 2   fwver       725208 non-null  object 
 3   quality_0   641388 non-null  float64
 4   quality_1   747961 non-null  object 
 5   quality_2   726857 non-null  float64
 6   quality_3   747972 non-null  int64  
 7   quality_4   747972 non-null  int64  
 8   quality_5   747928 non-null  object 
 9   quality_6   747972 non-null  int64  
 10  quality_7   747972 non-null  object 
 11  quality_8   747972 non-null  object 
 12  quality_9   747972 non-null  object 
 13  quality_10  747972 non-null  object 
 14  quality_11  747972 non-null  int64  
 15  quality_12  747972 non-null  int64  
dtypes: float64(2), int64(7), object(7)
memory usage: 91.3+ MB


In [41]:
np.unique(test_quality['quality_0'], return_counts = True)

(array([-1.,  0.,  1., ..., nan, nan, nan]),
 array([127001, 505710,   2319, ...,      1,      1,      1], dtype=int64))

In [30]:
len(test_quality['quality_2'].unique())

597

In [38]:
print(641388/747972)
print(641388/541)

0.8575026872663682
1185.5600739371534


In [34]:
726857/747972

0.9717703336488531

### train_data

##### err

In [5]:
train_err = pd.read_csv('./data/train_err_data.csv')
train_err

user_id            time model_nm       fwver  errtype errcode
0           10000  20201101025616  model_3  05.15.2138       15       1
1           10000  20201101030309  model_3  05.15.2138       12       1
2           10000  20201101030309  model_3  05.15.2138       11       1
3           10000  20201101050514  model_3  05.15.2138       16       1
4           10000  20201101050515  model_3  05.15.2138        4       0
...           ...             ...      ...         ...      ...     ...
16554658    24999  20201130163051  model_3  05.15.2138       15       1
16554659    24999  20201130172625  model_3  05.15.2138       16       1
16554660    24999  20201130172625  model_3  05.15.2138        4       0
16554661    24999  20201130172631  model_3  05.15.2138        4       0
16554662    24999  20201130210625  model_3  05.15.2138       15       1

[16554663 rows x 6 columns]

In [16]:
train_err.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16554663 entries, 0 to 16554662
Data columns (total 6 columns):
 #   Column    Dtype 
---  ------    ----- 
 0   user_id   int64 
 1   time      int64 
 2   model_nm  object
 3   fwver     object
 4   errtype   int64 
 5   errcode   object
dtypes: int64(3), object(3)
memory usage: 757.8+ MB


#####  problem

In [8]:
train_problem = pd.read_csv('./data/train_problem_data.csv')
train_problem

user_id            time
0       19224  20201102200000
1       23664  20201116140000
2       15166  20201114130000
3       12590  20201108210000
4       15932  20201103210000
...       ...             ...
5424    20167  20201125120000
5425    16270  20201110120000
5426    19114  20201106230000
5427    21505  20201104110000
5428    18822  20201102120000

[5429 rows x 2 columns]

In [17]:
train_problem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5429 entries, 0 to 5428
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  5429 non-null   int64
 1   time     5429 non-null   int64
dtypes: int64(2)
memory usage: 85.0 KB


##### quality

In [65]:
train_quality = pd.read_csv('./data/train_quality_data.csv',thousands = ',')
train_quality

time  user_id       fwver  quality_0  quality_1  quality_2  \
0       20201129090000    10000  05.15.2138        0.0          0        0.0   
1       20201129090000    10000  05.15.2138        0.0          0        0.0   
2       20201129090000    10000  05.15.2138        0.0          0        0.0   
3       20201129090000    10000  05.15.2138        0.0          0        0.0   
4       20201129090000    10000  05.15.2138        0.0          0        0.0   
...                ...      ...         ...        ...        ...        ...   
828619  20201124033000    24997  04.22.1778        0.0          0        0.0   
828620  20201124033000    24997  04.22.1778        0.0          0        0.0   
828621  20201124033000    24997  04.22.1778        0.0          0        0.0   
828622  20201124033000    24997  04.22.1778        0.0          0        0.0   
828623  20201124033000    24997  04.22.1778        0.0          0        0.0   

        quality_3  quality_4  quality_5  quality_6  quality_7  quality_8  \
0               0          0        0.0          0          0          0   
1               0          0        0.0          0          0          0   
2               0          0        0.0          0          0          0   
3               0          0        0.0          0          0          0   
4               0          0        0.0          0          0          0   
...           ...        ...        ...        ...        ...        ...   
828619          0          0        1.0          0          0          0   
828620          0          0        0.0          0          0          0   
828621          0          0        3.0          0          0          0   
828622          0          0        0.0          0          0          0   
828623          0          0        9.0          0          0          0   

        quality_9  quality_10  quality_11  quality_12  
0               0           4           0           0  
1               0           4           0           0  
2               0           4           0           0  
3               0           4           0           0  
4               0           4           0           0  
...           ...         ...         ...         ...  
828619          0          17           0           0  
828620          0          17           0           0  
828621          0          17           0           0  
828622          0          17           0           0  
828623          0          17           0           0  

[828624 rows x 16 columns]

In [73]:
train_quality.fwver

0         05.15.2138
1         05.15.2138
2         05.15.2138
3         05.15.2138
4         05.15.2138
             ...    
828619    04.22.1778
828620    04.22.1778
828621    04.22.1778
828622    04.22.1778
828623    04.22.1778
Name: fwver, Length: 828624, dtype: object

In [71]:
train_quality.corr()

time   user_id  quality_0  quality_1  quality_2  quality_3  \
time        1.000000 -0.001218  -0.003262   0.001618  -0.002101        NaN   
user_id    -0.001218  1.000000   0.006651  -0.002403   0.003458        NaN   
quality_0  -0.003262  0.006651   1.000000   0.004306   0.999535        NaN   
quality_1   0.001618 -0.002403   0.004306   1.000000   0.002976        NaN   
quality_2  -0.002101  0.003458   0.999535   0.002976   1.000000        NaN   
quality_3        NaN       NaN        NaN        NaN        NaN        NaN   
quality_4        NaN       NaN        NaN        NaN        NaN        NaN   
quality_5   0.002549 -0.002757   0.067673   0.010617   0.068949        NaN   
quality_6  -0.012737 -0.017612  -0.000135   0.028869   0.001121        NaN   
quality_7  -0.015707 -0.021609   0.000681   0.016226   0.000644        NaN   
quality_8   0.003519  0.004222  -0.001136   0.619596  -0.000181        NaN   
quality_9  -0.004334  0.007148   0.531695  -0.001262   0.478036        NaN   
quality_10  0.004219 -0.004560   0.032338   0.001312   0.029388        NaN   
quality_11  0.000724 -0.007521   0.006627   0.562785   0.006914        NaN   
quality_12  0.026708  0.019467   0.009599   0.002337   0.004986        NaN   

            quality_4  quality_5  quality_6  quality_7  quality_8  quality_9  \
time              NaN   0.002549  -0.012737  -0.015707   0.003519  -0.004334   
user_id           NaN  -0.002757  -0.017612  -0.021609   0.004222   0.007148   
quality_0         NaN   0.067673  -0.000135   0.000681  -0.001136   0.531695   
quality_1         NaN   0.010617   0.028869   0.016226   0.619596  -0.001262   
quality_2         NaN   0.068949   0.001121   0.000644  -0.000181   0.478036   
quality_3         NaN        NaN        NaN        NaN        NaN        NaN   
quality_4         NaN        NaN        NaN        NaN        NaN        NaN   
quality_5         NaN   1.000000   0.008326   0.009076   0.000228   0.037116   
quality_6         NaN   0.008326   1.000000   0.810524   0.000779   0.001073   
quality_7         NaN   0.009076   0.810524   1.000000   0.000982   0.001351   
quality_8         NaN   0.000228   0.000779   0.000982   1.000000  -0.000389   
quality_9         NaN   0.037116   0.001073   0.001351  -0.000389   1.000000   
quality_10        NaN   0.621752   0.012187   0.015014   0.000378   0.061430   
quality_11        NaN   0.024101   0.043297   0.026689  -0.000689  -0.001106   
quality_12        NaN   0.037750  -0.006372  -0.007758   0.010314   0.010548   

            quality_10  quality_11  quality_12  
time          0.004219    0.000724    0.026708  
user_id      -0.004560   -0.007521    0.019467  
quality_0     0.032338    0.006627    0.009599  
quality_1     0.001312    0.562785    0.002337  
quality_2     0.029388    0.006914    0.004986  
quality_3          NaN         NaN         NaN  
quality_4          NaN         NaN         NaN  
quality_5     0.621752    0.024101    0.037750  
quality_6     0.012187    0.043297   -0.006372  
quality_7     0.015014    0.026689   -0.007758  
quality_8     0.000378   -0.000689    0.010314  
quality_9     0.061430   -0.001106    0.010548  
quality_10    1.000000    0.005839    0.062462  
quality_11    0.005839    1.000000    0.056308  
quality_12    0.062462    0.056308    1.000000

In [72]:
train_quality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828624 entries, 0 to 828623
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   time        828624 non-null  int64  
 1   user_id     828624 non-null  int64  
 2   fwver       788544 non-null  object 
 3   quality_0   684192 non-null  float64
 4   quality_1   828624 non-null  int64  
 5   quality_2   788511 non-null  float64
 6   quality_3   828624 non-null  int64  
 7   quality_4   828624 non-null  int64  
 8   quality_5   828604 non-null  float64
 9   quality_6   828624 non-null  int64  
 10  quality_7   828624 non-null  int64  
 11  quality_8   828624 non-null  int64  
 12  quality_9   828624 non-null  int64  
 13  quality_10  828624 non-null  int64  
 14  quality_11  828624 non-null  int64  
 15  quality_12  828624 non-null  int64  
dtypes: float64(3), int64(12), object(1)
memory usage: 101.2+ MB


In [35]:
684192/828624

0.8256965764930777

In [36]:
788511/828624

0.9515908300990558

In [20]:
train_quality.columns

Index(['time', 'user_id', 'fwver', 'quality_0', 'quality_1', 'quality_2',
       'quality_3', 'quality_4', 'quality_5', 'quality_6', 'quality_7',
       'quality_8', 'quality_9', 'quality_10', 'quality_11', 'quality_12'],
      dtype='object')

In [57]:
arr = train_quality['quality_0']
arr[(arr>0)].unique()

array([2.00000e+00, 1.00000e+00, 3.00000e+00, 7.00000e+00, 6.00000e+00,
       4.08800e+03, 1.29000e+02, 3.18600e+03, 2.96000e+02, 1.70000e+01,
       6.30000e+01, 1.00000e+01, 9.04000e+02, 4.00000e+00, 3.79000e+03,
       1.62180e+04, 1.06280e+04, 1.04000e+02, 7.80000e+01, 3.79000e+02,
       3.46000e+02, 2.15000e+02, 2.61000e+02, 3.34000e+02, 2.50000e+02,
       1.60000e+01, 3.10000e+01, 8.70000e+01, 2.98000e+02, 1.50000e+01,
       7.70000e+01, 1.87140e+04, 7.42200e+03, 6.50000e+01, 1.40000e+01,
       3.30000e+01, 1.66000e+02, 1.94000e+02, 1.12000e+02, 1.26000e+02,
       5.23000e+02, 1.30000e+01, 9.40000e+01, 1.10000e+01, 4.25000e+02,
       3.20000e+01, 5.00000e+00, 1.98700e+03, 1.27270e+04, 5.20000e+01,
       2.14000e+02, 1.69000e+02, 2.03000e+02, 1.70000e+02, 1.31000e+02,
       1.14000e+02, 1.13000e+02, 6.10000e+01, 2.24000e+02, 1.84000e+02,
       6.90000e+01, 5.10000e+01, 7.20000e+01, 9.00000e+01, 9.10000e+01,
       1.19000e+02, 2.44000e+02, 2.09000e+02, 1.97000e+02, 4.990

In [46]:
train_quality['quality_0'].unique()

array([ 0.00000e+00,  2.00000e+00, -1.00000e+00,          nan,
        1.00000e+00,  3.00000e+00,  7.00000e+00,  6.00000e+00,
        4.08800e+03,  1.29000e+02,  3.18600e+03,  2.96000e+02,
        1.70000e+01,  6.30000e+01,  1.00000e+01,  9.04000e+02,
        4.00000e+00,  3.79000e+03,  1.62180e+04,  1.06280e+04,
        1.04000e+02,  7.80000e+01,  3.79000e+02,  3.46000e+02,
        2.15000e+02,  2.61000e+02,  3.34000e+02,  2.50000e+02,
        1.60000e+01,  3.10000e+01,  8.70000e+01,  2.98000e+02,
        1.50000e+01,  7.70000e+01,  1.87140e+04,  7.42200e+03,
        6.50000e+01,  1.40000e+01,  3.30000e+01,  1.66000e+02,
        1.94000e+02,  1.12000e+02,  1.26000e+02,  5.23000e+02,
        1.30000e+01,  9.40000e+01,  1.10000e+01,  4.25000e+02,
        3.20000e+01,  5.00000e+00,  1.98700e+03,  1.27270e+04,
        5.20000e+01,  2.14000e+02,  1.69000e+02,  2.03000e+02,
        1.70000e+02,  1.31000e+02,  1.14000e+02,  1.13000e+02,
        6.10000e+01,  2.24000e+02,  1.84000e+02,  6.900

In [70]:
train_quality['quality_3'].unique()

array([0], dtype=int64)

In [50]:
train_quality['quality_5'].unique()

array(['0', '4', '8', ..., '98,175', '7,998', '9,558'], dtype=object)

In [75]:
len(train_quality['quality_11'].unique())

12